### ISSUE TITLE
Keeping Original Pixiv File Name

### ISSUE THREAD

**Issue by YaaseenM** [hoppas0/ImgSearch#1]
Inside GetPixivImg.py, line 30 (# name = url.split("/")[-1]), which is commented out, allows the images downloaded from Pixiv to maintain their same pixiv file name. For example, it will keep the a file name of 123456789.p0.png. Having a release of main.rar with this line of code will be greatly appreciated.

**Comment by hoppas0** [comment]
收到

**Comment by hoppas0** [comment]
Now you can save the image as the original pixiv file name just by changing the naming method. If you encounter other questions, please feel free to ask me.
