### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by YaaseenM** [hoppas0/ImgSearch#2]
When trying to run the source code on my computer, I found it to be difficult to replicate the same executable you made through auto-py-to-exe since I have manually find and install all libraries involved. For example, I have to pip install loguru and other files not mentioned in the python code. Unfortunately, I was unable to replicate it as I could not find all the installations made on the project. Having a file name "requirements.txt" that contains all pip installations would be great. This would allow other people to run the program on their computer.

**Comment by hoppas0** [comment]
I tried adding a requirements .txt. Please let me know if it still has problems.
