### ISSUE TITLE
Suggestion for Failed Downloads

### ISSUE THREAD

**Issue by YaaseenM** [hoppas0/ImgSearch#3]
Having an additional folder for any files that have failed downloading would be nice as it could help separate and delete the old files that have not been downloaded by the original source. For example, having PixivImage folder are the successful downloads while having an additional folder like FailedImages that has all the images that are not in PixivImage. This could be done by copying the file from the source folder, like Tu, and then placed into the FailedImages folder.

**Comment by hoppas0** [comment]
Now the program will put the pictures that failed to download in the FailedImages folder. FailedImages folder and PixivImages folder are in the same folder.

If you have any other questions, please do let me know.
